-- INSERT INTO movies (movie_name)
-- VALUES ("Blade"),
--        ("Training Day"),
--        ("Spider Man"),
--        ("Iron Man"),
--        ("Thor"),
--        ("BatMan"),
--        ("Day Man"),
--        ("Night Man");
